"""initial_schema

Revision ID: d954c63ca7b1
Revises: 
Create Date: 2026-09-11 14:27:07.829318+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd954c63ca7b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending_triage', 'ready_to_commit', 'committed', name='complaint_status'), nullable=False),
    sa.Column('complaint_source', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_strength_grade', sa.String(length=100), nullable=True),
    sa.Column('batch_lot_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('affected_quantity', sa.String(length=100), nullable=True),
    sa.Column('originating_site_block', sa.String(length=200), nullable=True),
    sa.Column('impacted_npm', sa.Text(), nullable=True),
    sa.Column('complaint_category', sa.String(length=100), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('severity_suggested', sa.Enum('critical', 'major', 'minor', 'not_assessed', name='severity_level'), nullable=True),
    sa.Column('severity_final', sa.Enum('critical', 'major', 'minor', 'not_assessed', name='severity_level_final'), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', 'not_assessed', name='priority_level'), nullable=True),
    sa.Column('suggested_next_action', sa.Text(), nullable=True),
    sa.Column('initial_risk_assessment', sa.Text(), nullable=True),
    sa.Column('raw_source_text', sa.Text(), nullable=True),
    sa.Column('raw_source_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.Enum('ai', 'user', name='audit_actor'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.String(length=20), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('audit_log')
    op.drop_table('complaints')
    # ### end Alembic commands ###
